// <auto-generated />
namespace Forum.Framework.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _0055 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_0055));
        
        string IMigrationMetadata.Id
        {
            get { return "201701112255587_0055"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
