// <auto-generated />
namespace Forum.Framework.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _0035 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_0035));
        
        string IMigrationMetadata.Id
        {
            get { return "201701112235571_0035"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
